{{- if and .Values.gateway.enabled (eq (include "zelkor-platform.gatewayCreateGatewayClass" . | trim) "true") .Values.gateway.envoyProxy (hasKey .Values.gateway.envoyProxy "enabled") .Values.gateway.envoyProxy.enabled }}
{{- $ep := .Values.gateway.envoyProxy -}}
{{- $svc := $ep.service | default dict -}}
{{- $svcType := $svc.type | default "" -}}
{{- $ns := $ep.nodeSelector | default dict -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "zelkor-platform.fullname" . }}-envoy-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zelkor-platform.labels" . | nindent 4 }}
spec:
  logging:
    level:
      default: {{ include "zelkor-platform.vendorLogLevel" (dict "root" . "component" .Values.gateway "vendor" "envoy") }}
  provider:
    type: Kubernetes
    kubernetes:
      {{- if $svcType }}
      envoyService:
        type: {{ $svcType | quote }}
      {{- end }}
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              strategy:
                type: RollingUpdate
                rollingUpdate:
                  maxSurge: 0
                  maxUnavailable: 1
              {{- if or $ns $ep.hostNetwork }}
              template:
                spec:
                  {{- if $ns }}
                  nodeSelector:
                    {{- toYaml $ns | nindent 20 }}
                  {{- end }}
                  {{- if $ep.hostNetwork }}
                  hostNetwork: true
                  dnsPolicy: ClusterFirstWithHostNet
                  {{- end }}
              {{- end }}
        {{- with $ep.resources }}
        container:
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
