{{- if and .Values.gateway.enabled .Values.gateway.envoyProxy (hasKey .Values.gateway.envoyProxy "enabled") .Values.gateway.envoyProxy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "zelkor-platform.fullname" . }}-envoy-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zelkor-platform.labels" . | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              strategy:
                type: RollingUpdate
                rollingUpdate:
                  maxSurge: 0
                  maxUnavailable: 1
              template:
                spec:
                  nodeSelector:
                    ingress-ready: "true"
                  hostNetwork: {{ .Values.gateway.envoyProxy.hostNetwork | default false }}
                  {{- if .Values.gateway.envoyProxy.hostNetwork }}
                  dnsPolicy: ClusterFirstWithHostNet
                  {{- end }}
{{- end }}
