{{- if and .Values.postgresql.enabled (eq .Values.databases.mode "in-cluster-basic") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zelkor-platform.fullname" . }}-postgresql
  labels:
    {{- include "zelkor-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | default "zelkor-dev-password" | quote }}
  password: {{ .Values.postgresql.auth.password | default "zelkor-dev-password" | quote }}
  username: {{ .Values.postgresql.auth.username | default "zelkor" | quote }}
  database: {{ .Values.postgresql.auth.database | default "zelkor" | quote }}
{{- end }}
